<?php

namespace App\Services;

use App\Models\Certificate;
use App\Models\CertificateTemplate;
use App\Models\Cohort;
use App\Models\CohortEnrollment;
use App\Models\User;
use App\Jobs\Certificate\GenerateCertificatePdf;
use Illuminate\Support\Str;

class CertificateService
{
    public function generateForCohort(Cohort $cohort): array
    {
        $template = $cohort->certificateTemplate ?? CertificateTemplate::where('is_default', true)->first();
        if (!$template) throw new \RuntimeException('No certificate template configured.');

        $threshold = $cohort->completion_threshold ?? 70;
        $generated = [];

        $eligibleEnrollments = CohortEnrollment::where('cohort_id', $cohort->id)
            ->where('completion_percent', '>=', $threshold)
            ->where('certificate_issued', false)
            ->with('student')
            ->get();

        foreach ($eligibleEnrollments as $enrollment) {
            if ($enrollment->student->id_verification_status !== 'approved') continue;

            $certificate = $this->generate($enrollment, $template, $cohort);
            $enrollment->update(['certificate_issued' => true]);
            $generated[] = $certificate;
        }

        return $generated;
    }

    public function generate(CohortEnrollment $enrollment, CertificateTemplate $template, Cohort $cohort): Certificate
    {
        $uuid = (string) Str::uuid();
        $certNumber = 'CERT-' . now()->format('Y') . '-' . str_pad(Certificate::count() + 1, 6, '0', STR_PAD_LEFT);

        $certificate = Certificate::create([
            'uuid' => $uuid,
            'student_id' => $enrollment->student_id,
            'cohort_id' => $cohort->id,
            'enrollment_id' => $enrollment->id,
            'template_id' => $template->id,
            'certificate_number' => $certNumber,
            'qr_code_path' => null, // Will be generated by job
            'pdf_path' => null, // Will be generated by job
            'verification_url' => url("/verify/{$uuid}"),
            'issued_at' => now(),
            'metadata' => [
                'student_name' => $enrollment->student->name,
                'cohort_title' => $cohort->title,
                'cohort_type' => $cohort->type->value,
                'completion_percent' => $enrollment->completion_percent,
                'instructor_name' => $cohort->instructor->name ?? 'Instructor',
            ],
            'created_at' => now(),
        ]);

        GenerateCertificatePdf::dispatch($certificate);

        return $certificate;
    }
}
